### ISSUE TITLE
Is it possible to run multiple Sandbox Instances at the same time?

### ISSUE THREAD

**Issue by unikzforce** [thesecretclub/SandboxBootkit#5]
I'm currently thinking to how to circumvent the current limitation of singleton windows sandbox instance.

Trying to learn Reverse engineering to nullify this limitation.

If this is happening one can simply create a windows container runtime environment with GUI support and also create a kubernetes integration with it.

Are you interested to take part in this effort?

**Comment by mrexodia** [comment]
No idea, but it’s not really related to this repository…
